### ISSUE TITLE
ÜBUNG: Erstelle ein Issue aus Abschnitt 2, Lektion 6 GitHub Turorial

### ISSUE THREAD

**Issue by Ah3n0** [LMStudent/hallo-github#10]
Hallo @suchja ,

zum Abschluss der o.a. Aufgabe versuche ich mich an einem neuen Issue. 
Aktuell habe ich noch keine brennenden Fragen, aber das wird sich sicherlich bald ändern. 

Beste Grüße

Ah3

**Comment by suchja** [comment]
@Ah3n0 Super Start und willkommen auf GitHub! Du weißt ja jetzt wie du mich erreichst und ich hoffe bald wieder von dir zu hören.

Übrigens, ein Commit kann entweder der Projektinhaber (bzw. das entsprechende Team) machen, oder auch der Ersteller des Issues. Probier doch gleich mal dies Issue wieder zu schließen!

**Comment by suchja** [comment]
@Ah3n0 Sehr gut! Du kannst übrigens auch ein Issue kommentieren welches schon geschlossen ist. Ebenfalls kannst du (als Ersteller) oder auch der Projektinhaber das Issue wieder eröffnen.
