### ISSUE TITLE
Danke für den Udemy-Kurs!

### ISSUE THREAD

**Issue by holginaut** [LMStudent/hallo-github#102]
Hallo @suchja, ich möchte mich #74 ebenfalls anschließen und mich für den tollen Kurs bedanken und die Aufgabe hiermit abschließen. ;-)

**Comment by suchja** [comment]
Sehr gut! Freut mich sehr, dass du auch die Aufgabe machst. Damit herzlich willkommen auf GitHub und bei [LernMoment.de](https://www.lernmoment.de). 

Du also Autor dieses Issues kannst auch das Issue wieder schließen. Magst du das vielleicht gleich mal ausprobieren?

**Comment by holginaut** [comment]
Na klar! ;-)
