### ISSUE TITLE
Übung zum Kurs Grundlagen GitHub

### ISSUE THREAD

**Issue by ElbPsi** [LMStudent/hallo-github#112]
Bisher finde ich den Kurs sehr gut.
- Inhaltlich: Genau das Richtige, was ich als Dummy brauche
- Gute Grammatik und Aussprache, keine Füllwörter
- Ergänzung der Sprache durch Grafiken

**Comment by suchja** [comment]
@ElbPsi Vielen Dank und herzlich willkommen auf GitHub und bei [LernMoment.de](https://www.lernmoment.de)!!! Insbesondere vielen Dank, dass du eine so tolle Bewertung auch bei Udemy abgegeben hast!

Wie ich sehe verbindest du es auch gleich damit hier ein paar Dinge von Markdown auszuprobieren.

Du als Autor eines Issues kannst dieses auch wieder schließen. Dazu brauchst du lediglich unten auf den Button "Close Issue" klicken. Ausser dir als Autor eines Issues kann ansonsten nur der Projektinhaber (in diesem Fall ich) das Issue schließen, aber alle anderen GitHub-Benutzer können ebenfalls an dem Issue kommentieren.

Magst du das Schließen mal ausprobieren???
