### ISSUE TITLE
Issue Tags

### ISSUE THREAD

**Issue by felixdittrich92** [LMStudent/hallo-github#115]
@suchja Wie kann ich bestimmte Tags wie bug/question etc. erstellen ?
Also angenommen jemand erstellt ein neues Issue dann sollte er zuerst gefragt werden zu welchem "Bereich" er die Issue erstellt

**Comment by felixdittrich92** [comment]
ok habs :)

**Comment by suchja** [comment]
Spannend Frage. Wie ist deine Lösung?

Das was du schilderst ist so glaube ich direkt nicht möglich, oder? Das einzige was ich finden konnte ist, dass es die Möglichkeit gibt Labels für ein Template zu definieren. Du könntest also verschiedene Templates mit unterschiedlichen Labels definieren und der Issue-Schreiber sucht sich dann ein passendes Template aus.

Achja, bei den Issues heißt das Label und nicht Tag ;-)

**Comment by suchja** [comment]
Übrigens, als Autor kannst du dein Issue auch selber schließen, wenn es beantwortet ist. (Du oder der Projektinhaber können es dann später auch nochmals öffnen, falls es noch Diskussionsbedarf gibt).

Das kannst du ja ausprobieren, wenn deine Frage hier beantwortet ist.

**Comment by suchja** [comment]
Das ging schnell 😉. Wie du siehst kann man auch an einem geschlossenen Issue kommentieren.

**Comment by felixdittrich92** [comment]
Unter settings -> Issues gibt es einen Button set templates dort kann man quasi erstellen das die user davor auswählen zu welchem Thema sie das Issue erstellen :)

**Comment by suchja** [comment]
Das ist was ich meinte ;-).
