### ISSUE TITLE
Wieso die Motivation?

### ISSUE THREAD

**Issue by itsnils** [LMStudent/hallo-github#119]
Übung:
Ich bin gerade auf Udemy unterwegs und schaue den Kurs über GitHub an. Die frage an @suchja 
was motiviert dich dieses Projekt zu unterhalten?
Übung ende :)

**Comment by suchja** [comment]
@itsnils Moin, herzlich willkommen auf GitHub und ich freue mich, dass dir einige Tutorials/Videos von [LernMoment.de](https://www.lernmoment.de) gefallen.

Entschuldige, dass ich deine Frage so lange vor mir her geschoben habe. Ich dachte, dass ich dazu gut ein Video machen könnte, aber soweit bin ich noch nicht gekommen und mittlerweile hatte ich deine Frage auch schon wieder vergessen 😇.

Hauptsächlich motiviert mich, dass ich professionelle Softwareentwicklung als überaus wichtig empfinde. Für mich ist es wichtig, dass bei jeder Entwicklung der Kundennutzen im Fokus steht. Ich habe bereits sehr viel schlechte Software (sowohl vom Quellcode wie auch von der tatsächlich Anwendung) gesehen und denke mir immer, dass es für den Auftraggeber (oder manchmal auch den Benutzer) Geldverschwendung ist und für die Entwickler eine große Zeitverschwendung.

Daher motiviert mich jeder Einsteiger in die Programmierung der den Ehrgeiz hat zu verstehen, dass es einen Unterschied zwischen Programmierung und Softwareentwicklung gibt. Für mich steht die Verwendung einer Versionsverwaltung und die Kooperation mit anderen Entwicklern ganz weit oben bei den Praktiken eines professionellen Softwareentwicklers. GitHub kombiniert beides und versüsst es mit coolen OpenSource-Projekten und natürlich jeder Menge Potential für Anfänger erste kleine Entwicklungsarbeiten zu übernehmen.

Mir ist auch klar, dass in der Welt des Lernen mit Onlinekursen, in der ich mich mittlerweile bewege, die Praxis häufig auf der Strecke bleibt. Das demotiviert die Lernenden spätestens dann, wenn sie einiges an Zeit in Videos investiert haben und bei der ersten einfachen Aufgabe feststellen, dass sie es eigentlich gar nicht können.
In meiner Laufbahn hatte ich häufig das Glück, dass ich erfahrenen Entwicklern über die Schulter schauen konnte, Fragen konnte und es dann selber ausprobiert habe. Genau dieses Erlebnis mache ich (teilweise) für meinen Erfolg verantwortlich und möchte es anderen jetzt auch ermöglichen. Darüberhinaus hilft es mir zu sehen wie Leute mit meinen Übungen zurecht kommen und wo vielleicht noch Verbesserungspotential für mich ist.

**Fazit:** Dieses Projekt ist total egoistisch, weil ich davon ausgehe, dass es so weniger schlechte Programmierer gibt und ich weniger schlechten Quellcode lesen muss :grins

**Comment by suchja** [comment]
Wie du siehst kann man auch kommentieren, wenn ein Issue bereits geschlossen ist. (das wieder öffnen war eben nur ein versehen von mir ;).

**Comment by suchja** [comment]
PS: Was treibt dich auf GitHub?

**Comment by itsnils** [comment]
Hallo Jan

Villen dank für deine Nachricht und deine Zeit.

Ja die Zeit vergeht schnell😊
Ich finde man sieht deine Motivation in den Videos das ist toll. Und auch deine Geschichte die du erklärt hast. 
Du könntest anderen programmieren über die Schultern schauen das sehr viel wert und wenn du den Ehrgeiz hast selber das zu optimieren/besser zu sein ist das genial zugleich noch Freude daran – Bingo😊
das mit der Versionsverwaltung ist schon einen zentralen Punkt. Was die Professionalität enorm steigert. Lange habe ich GitHub nicht verstanden, weil es anfangs so abstrakt klingt. Als normaler Windows/Mac Benutzer mit optischem Ordner und Icons ist es schwer sich da was anders/besseres vorzustellen.. Aber im Nachhinein - GitHub ist genial! Und gar nicht so abstrakt.

Zu mir. Ich hatte vor einem Jahr begonnen Python zu lernen. Ich war schon immer begeistert von elektronischen Geräten und dessen Funktionen/Möglichkeiten. Mit dem Arduino und dem Raspberry Pi haben sich da extrem grosse Türen geöffnet und die Sensoren und Aktoren die mit Mikrocontrollern angesprochen werden können wachsen täglich. Die Möglichkeiten mit dem Raspberry Pi und Python sind fast grenzenlos. MicroPython für Mikrocontroller wird auch immer beliebter. Es ist eine schnelllebige zeit aber sehr spannend.

Wenn du magst, kannst du mir noch eine Frage zu GitHub beantworte?
Folgendes Szenario: Es existiert ein GitHub Account für einen Verein oder eine Firma. Sagen wir mal der Account heisst «pi-team» und ich als @itsnils oder du als @suchja  erhalten von pi-team einen Auftrag «Webseite». Wie wird das professionell umgesetzt? Erstellt pi-team ein leeres Repository «Webseite» und wir machen einen Fork davon? Im Fork arbeiten wir und fügen unseren Code hinzu und machen dann einen Pull request zu «pi-team» wenn wir soweit fertig sind.?


Liebe grüsse aus Basel
Janique

**Comment by suchja** [comment]
Hallo Janique,

vielen Dank für deine Antwort. Momentan klappt das irgendwie nicht mit meinen Antworten hier bei GitHub 🙄. Entschuldige.

Bezüglich deiner Frage ist eine Antwort nicht ganz so einfach, weil es viele verschiedene Möglichkeiten und Einflüsse gibt. ABER, sagen wir mal, dass `pi-team` ein Auftraggeber ist, der die Kontrolle über seinen Quellcode behalten möchte (was impliziert, dass Leute beim Auftraggeber Softwareentwickler sind), dann wäre dein Ansatz genau der richtige. Dabei bedenken solltest du, dass PullRequest üblicherweise auf Feature-Ebene gemacht werden. D.h. wenn eine Funktionalität (sagen wir z.B. der Login auf eine Webseite) fertig gestellt ist, dann wird ein PullRequest erstellt. In diesem Szenario hätte dein Auftraggeber also einiges zutun um die PullRequests anzuschauen und dann in das Projekt zu mergen. Der Auftraggeber muss also ein gutes Verständnis von Softwareentwicklung haben.

Eine Alternative wäre, dass du selber mit deinem Account @itsnils ein Verzeichnis erstellst, darin alle Commits machst und bei Abschluss des Auftrags das Verzeichnis an deinen Auftraggeber überträgst.

Eine weitere Möglichkeit wäre, dass zwar dein Auftraggeber das Verzeichnis erstellt, aber dich als Collaborator in das Projekt einlädt. Dann kannst du Commits machen auch ohne, dass dein Auftraggeber viele PullRequests bearbeiten muss.

Neben diesen Möglichkeiten gibt es noch einige andere. GitHub ist also ziemlich flexibel. Das ist sowohl Vorteil wie auch Nachteil. Gerade als Einsteiger ist es manchmal schwierig selber einen guten Prozess zu definieren.

gitHub versucht selber einem da etwas unter die Arme zugreifen mit dem [GitHub Flow](https://guides.github.com/introduction/flow/). Je nachdem wie du dich auskennst kann es dir vielleicht ein wenig helfen.

Soviel fürs erste. Würde mich freuen, wenn du mir irgendwann schreibst wie du es tatsächlich umgesetzt hast und was deine Erfahrungen damit sind.

Liebe Grüße
Jan von [LernMoment.de](https://www.lernmoment.de)
