### ISSUE TITLE
Test issue: Ist in dem Projekt Webseite gemacht?

### ISSUE THREAD

**Issue by ARDegen** [LMStudent/hallo-github#122]
@suchja Ich habe gerade aus Deinem Kurs Tutorial: Grundlagen von GitHub - Fork, Pull Request und Co. gerade gelernt wie ich ein Issue erstelle. Das ist mein erste Versuch.
Ist dieses Projekt der Erstellung einer Seite gewidmet?

**Comment by suchja** [comment]
@ARDegen erstmal herzlichen Glückwunsch zu deinem ersten Issue und willkommen bei LernMoment und GitHub.

Dieses Projekt beschäftigt sich nicht wirklich mit dem Erstellen einer Seite. Vielmehr geht es darum zu sehen wie GitHub so funktioniert.

Was für eine Seite möchtest du denn erstellen? Eine GitHub-Page? Das habe ich Hier https://youtu.be/TvJXACCwkC8 und hier https://youtu.be/1w-kAGBxMpc erklärt. 

Ansonsten beschreibe mir doch kurz was du machen möchtest und ich kann dir vielleicht ein paar Tipps geben. 

Viele Grüße 
Jan von LernMoment.de

**Comment by suchja** [comment]
Ich schließe dieses Issue mal, weil ich bisher nichts weiter von dir gehört habe.
