### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by jgonser** [LMStudent/hallo-github#125]
Hallo Jan,
danke für den tollen GitHub Kurs!
Schön wäre noch ein Abschnitt zum Thema *merge* und Auflösen von *merge conflicts*.
Viele Grüße!

**Comment by suchja** [comment]
@jgonser Hallo und willkommen auf GitHub und LernMoment.de!
Hast du den kostenlosen oder kostenpflichtigen Kurs belegt?

Grundsätzlich stimme ich dir zu, dass ich dieses Thema bisher noch nicht abgedeckt habe. Ich muss mal überlegen wie und wo ich das aufnehme. *Merge* ist ja ein reines Git-Thema. Aber schauen wir mal.

Vielen Dank für deine Rückmeldung und weiterhin viel Spaß und Erfolg mit GitHub
Jan von [LernMoment](https://www.lernmoment.de)

**Comment by suchja** [comment]
@jgonser Als Autor dieses Issues kannst du es auch wieder schließen. Dieses "Recht" haben nur der Autor und der Projektinhaber (also ich in diesem Fall).

Magst du es mal ausprobieren?

**Comment by suchja** [comment]
Und nicht die weiteren Übungen (z.B. PullRequest) vergessen 😉

**Comment by jgonser** [comment]
Ich habe den kostenlosen Kurs belegt. Normalerweise arbeite ich mit Mercurial und DiffMerge. Ich wollte eben mal erfahren, wie der Merge bei GitHub abläuft und welche Tools dort verwendet werden.

**Comment by suchja** [comment]
Dann brauchst du natürlich keine weiteren Übungen 🤣!

GitHub selber hat kein Tool fürs Merging. Es ist ja eigentlich nur ein Git-Server mit zusätzlicher Web-.Oberfläche für Issues und Co. Natürlich ist in *GitHub Desktop* einer Cross-plattform Anwendung für die einfacherer lokale Bedienung von GitHub das Merging integriert. Ansonsten nehme ich in Visual Studio Code und Visual Studio die jeweiligen Git-Integrationen bzw. Extensions. Damit läuft alles wunderbar. Aber wahrscheinlich hast du eine andere IDE, oder?

**Comment by jgonser** [comment]
Ich benutze IntelliJ IDEA (Java) und Rider (C#) von JetBrains. Die entsprechende Git-Integrationen muss ich mal ausprobieren. Hast du Erfahrungen mit dem Tool Sourcetree?

**Comment by suchja** [comment]
Rider, cool, wie gefällt es dir?

Mit Sourcetree habe ich bisher noch nicht gearbeitet. Ich hatte mal kurz GitHub Desktop, aber da sah ich keinen Vorteil im Vergleich zur Integration in Visual Studio.

PS: Wie du siehst kann man auch in einem geschlossenen Issue noch kommentieren und es natürlich auch wieder öffnen (sowohl du wie auch ich).

**Comment by jgonser** [comment]
Also Visual Studio ist meiner Meinung nach nur mit der Erweiterung ReSharper von JetBrains wirklich produktiv nutzbar. Allerdings merkt man auch, dass diese Erweiterung die Geschwindigkeit und Responsiveness bremst. 

Ich nutze schon Jahre lang Intellij Idea von JetBrains und halte sie für die beste IDE für die Java Entwicklung. Na ja und Rider ist halt eigentlich Intellij Idea für C#: super schnell und hat all die coolen Features und Refactorings von Idea. Leider gibt es meines Wissens keine kostenlose Community Edition.

Nutzt du den die Git Integration in Visual Studio auch um größere Merges mit vielen Dateien und Konflikten durchzuführen?
