### ISSUE TITLE
ÜBUNG: Erstelle ein Issue, Abschnitt 2, Lektion 6

### ISSUE THREAD

**Issue by Stephan-Wolf** [LMStudent/hallo-github#13]
@LMStudent : Wie in Deinem Udemy-Kurs gewünscht

Bisher noch keine Fragen. Aber die könnten noch kommen ;-)

**Comment by suchja** [comment]
@Stephan-Wolf Super! Immer her mit den Fragen 😉!

Da du Autor von diesem Issue bist, kannst du es auch schließen. Probier es doch gleich mal aus! Beobachte dabei auch wie das Label oben unter der Überschrift von Grün (mit Text "Open") auf Rot (mit Text "Closed") wechselt.

Ich hoffe ein Fork oder PullRequest ist auch schon in Arbeit. Bin schon sehr gespannt.

**Comment by Stephan-Wolf** [comment]
Na dann schließe ich mal.

**Comment by suchja** [comment]
Sehr gut! Man kann übrigens auch dann noch weiter kommentieren, wenn das Issue geschlossen wurde. Auch das nachträgliche öffnen ist möglich.
