### ISSUE TITLE
Schreibweise

### ISSUE THREAD

**Issue by AVAgatoah** [LMStudent/hallo-github#135]
Hallo LMStudent,

im Erklärtext ist "true" groß geschrieben. Macht das einen Unterschied?

Danke im Voraus

**Comment by suchja** [comment]
@AVAgatoah Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Deine Frage: 

> im Erklärtext ist "true" groß geschrieben. Macht das einen Unterschied?

verstehe ich nicht ganz. Auf welchen "Erklärtext" beziehst du dich? Kannst du mir vielleicht ein paar Zeilen hier hinein kopieren (also in einem neuen Kommentar)? Dann werde ich umgehend dir eine klar Antwort geben können.

Nachdem du ja nun bereits ein Issue angelegt hast, kannst du ja direkt weitergehen zum PullRequest!

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
Hoffentlich hat sich deine Frage mittlerweile erledigt. Wenn nicht, bitte einfach das Issue erneut öffnen!
