### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by Schwenksen** [LMStudent/hallo-github#138]
Hallo,
dies ist ein Test Issue zum Üben der github Grundfunktionen und kann auch gerne wieder getilgt werden, da kein wirklicher, inhaltlicher Beitrag. :-)
Gruß in die Republik

**Comment by suchja** [comment]
@Schwenksen  Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Wusstest du, dass du dieses Issue selber schließen kannst? Sowohl der Autor (also in diesem Fall du) wie auch der Projektinhaber (in diesem Fall ich) können ein Issue schließen. Du kannst es ja an diesem Issue mal ausprobieren. 

Nachdem du ja nun bereits ein Issue angelegt hast, kannst du direkt weitergehen zum PullRequest!

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by Schwenksen** [comment]
Issue geschlossen, da erledigt.

@suchja Vielen Dank für die Interaktion
