### ISSUE TITLE
Erste eigene Issue

### ISSUE THREAD

**Issue by klatoo** [LMStudent/hallo-github#14]
GitHub-Tutorial Abschnitt 2 - Lektion 6

Hürde übersprungen ;) sogar mit **etwas** Markdown.

Ein *kleiner* Schritt für den Entwickler, aber ein **großer** Schritt...

**Comment by suchja** [comment]
@klatoo 🚀 Herzlichen Glückwunsch! 🚀 

Wenn du sicher gehen willst, das jemand bestimmtest (in diesem Beispiel ich) dein Issue oder dein Kommentar sieht, dann solltest du ihn in dem Issue erwähnen. Schreibe einfach ein @ und wähle dann den passenden Namen aus.
Viel Leute auf GitHub haben die Benachrichtigungen so eingestellt, dass sie nur eine Mail bekommen, wenn ihr Name explizit erwähnt wird.

Weiterhin viel Spaß!

**Comment by suchja** [comment]
ein Issue schließen kannst du ja schon. Daher mache ich das mal hier.
