### ISSUE TITLE
Github issue 

### ISSUE THREAD

**Issue by ConCoiner** [LMStudent/hallo-github#145]
@Juergen-Busch 
Hallo 
danke für das Projekt. 
Das ist mein Issue, Tutorial Github auf udemy. 
Ich wünsche dir noch einen erfolgreichen Tag. :)

**Comment by suchja** [comment]
@ConCoiner Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Wusstest du, dass du dieses Issue selber schließen kannst? Sowohl der Autor (also in diesem Fall du) wie auch der Projektinhaber (in diesem Fall ich) können ein Issue schließen. Du kannst es ja an diesem Issue mal ausprobieren. 

Nachdem du ja nun bereits ein Issue angelegt hast, kannst du direkt weitergehen zum PullRequest!

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

PS: Hast du etwas mit Juergen-Busch zutun? Du hast ihn ja als erstes im Issue genannt (über das @). Mein Benutzername mit dem du mich erreichen kannst ist @suchja 

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
Ich schließe das Issue dann mal selber 😁
