### ISSUE TITLE
Kein Compare & pull request button nach push

### ISSUE THREAD

**Issue by klatoo** [LMStudent/hallo-github#15]
Hi, ich habe einen fork erstellt, in Program.cs in Zeile 85 meinen Namen hinzugefügt,
danach commit und push. Bekomme jetzt allerdings nicht den Button "Compare & pull request"

siehe:
![grafik](https://cloud.githubusercontent.com/assets/2091825/21328836/0a2bc408-c636-11e6-9202-19577e697868.png)

**Comment by klatoo** [comment]
Ach ja, "update" habe ich natürlich gemacht (mehrfach) ;)

**Comment by klatoo** [comment]
Hoppla, wollte natürlich nicht schließen.... sorry

**Comment by klatoo** [comment]
Mir ist aufgefallen, dass in deinem Beispiel ein branch erwähnt wird, kann das evtl. daran liegen?

**Comment by klatoo** [comment]
Mit "New pull request" geht es allerdings auch

**Comment by suchja** [comment]
@klatoo danke für deine Rückmeldung. Muss ich mir mal anschauen und ausprobieren. Eigentlich erscheint immer sehr konsequent die Möglichkeit einen Pull Request zu erstellen. Vielleicht ist es tatsächlich der fehlende Branch.
Habe ich im Kurs nicht gesagt, dass ein Branch erstellt werden soll?

**Comment by klatoo** [comment]
Hmm, schätze mal wir können das jetzt schließen ;)

**Comment by suchja** [comment]
@klatoo Hat es denn final funktioniert? Entschuldige, dass ich das aus den Augen verloren habe :worried:
