### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by stefangermer** [LMStudent/hallo-github#152]
Hallo,
danke für das selbsterklärende Tutorial :-).

Gruß

Stefan

**Comment by suchja** [comment]
@stefangermer Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest ;-)!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by stefangermer** [comment]
cy later
