### ISSUE TITLE
Übung: erstelle ein Issue

### ISSUE THREAD

**Issue by DerBlauerRitter** [LMStudent/hallo-github#154]
Da haben wir es.

**Comment by DerBlauerRitter** [comment]
War nur zur Übung.

**Comment by suchja** [comment]
@DerBlauerRitter Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Wie du bereits festgestellt hast, kannst du als Autor das Issue schließen und auch nachdem es geschlossen ist noch kommentieren. Außerdem kannst du es sogar wieder öffnen. Das Schließen und wieder öffnen ist jedoch dem Autor (also dir) und dem Projektinhaber (also mir) bzw. eingetragenen Mitarbeitern (auch Collaborator genannt) vorbehalten.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
