### ISSUE TITLE
Das erste Issue

### ISSUE THREAD

**Issue by MK-NEUKO** [LMStudent/hallo-github#156]
@suchja 
Hallo Jan, sehr praxisorientierter Kurs, das ist genau das, was ich in vielen Fachbüchern immer vermisse.

**Comment by MK-NEUKO** [comment]
Zur Erklärung, ich mache gerade den GitHub Kurs und den C# Kurs auf Udemy. Das ist sozusagen Übung eins vom GitHun Kurs.

**Comment by suchja** [comment]
@MK-NEUKO Hallo und willkommen auf GitHub! Freut mich sehr, dass du an Kursen von [LernMoment.de](https://www.lernmoment.de/kurse) teilnimmst und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
