### ISSUE TITLE
erstes Issue 

### ISSUE THREAD

**Issue by agrib-01** [LMStudent/hallo-github#159]
Hi @suchja,
danke für die Möglichkeit hier ein Issue erstellen zu können.
Ich werde auch gleich mal probieren diesen Issue zu schließen so wie es hier  #153 schon erwähnt ist. 

Gruß 
agrib-01

**Comment by suchja** [comment]
@agrib-01 Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast (inkl. dem Schließen), kannst du ja direkt weitergehen zum PullRequest!

Wie du siehst kann man auch einen Kommentar an ein Issue hängen, wenn dieses schon geschlossen ist.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
