### ISSUE TITLE
Fork wieder entfernen 

### ISSUE THREAD

**Issue by agrib-01** [LMStudent/hallo-github#161]
Hi @suchja,
du hast in deinem Udemy Kurs gezeigt wie man sich einen Fork von einem Projekt in seinen Bereich rein holt. 
Jetzt hab ich den Pull request gemacht und es hat auch alles soweit funktioniert aber kann ich den Fork jetzt auch aus meinem Bereich wieder löschen? 

Gruß 
agrib-01

**Comment by suchja** [comment]
@agrib-01 Moin 😁! 

Ja, sobald du den PullRequest erstellt hast, kannst du theoretisch den Fork wieder löschen. Da es jedoch passieren kann, dass noch Änderungen erbeten werden, könntest du den Fork bestehen lassen, bis der PullRequest akzeptiert ist. Musst du aber nicht.
