### ISSUE TITLE
Tutorial: Grundlagen von GitHub Issue erstellen

### ISSUE THREAD

**Issue by AndresRedondo87** [LMStudent/hallo-github#162]
Guten Tag,
Hiermit wollte ich die Aufgabe von Abschnitt2, Video 6 erledigen.
Ich lerne noch weiter, ich werde mich die Repository von LMStudent/hallo-octocat auch anschauen.

EDIT:
Ich hatte Probleme beim Änderungen zu pushen.
ich hatte am Anfang diese Repository einmal geklont vor lange Zeit und dann diese gleiche Repository in ein Ordner mit ein anderen Name geforkt. Dann dürfte ich gar nicht pushen, da ich keine Berechtigung von LMStudent hatte.
Ich bin zuemplich sicher das ich auf den Fork gearbeitet hatte. Habe ich etwas missverstanden oder darf man sowas gar nicht? (eine Repository mehrmals lokal haben, in mein Fall einmal als klon und einmal als Fork)
Kommt dann Github damit durcheinaner oder bin ich durcheinander gekommen?

Ich habe einfach beide lokale Ordner gelöscht und nur einmal fork gemacht und scheinbar hat es prima funktioniert. :)
Diese Frage hier wird nir als Kommentar gespeichert? wäre es vielleicht interessant als Issue, @suchja ?
(EDIT END)

Vielen Dank,
Andrés

**Comment by AndresRedondo87** [comment]
Jezt habe ich doch eine Frage für dich, @suchja :

Die "Mitteilungen" beim Fehlerliste kann man immer ignorieren? 
Manchmal habe ich hunderten davon gesehen aber das Programm funktionierte in Ordnung...
Wann könnten sie wichtig sein?

Danke im Voraus,
Andrés

**Comment by suchja** [comment]
@AndresRedondo87 Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
@AndresRedondo87 Bezüglich deiner Frage:
> Jezt habe ich doch (noch) eine kleine Frage für dich, @suchja :
> 
> Die "Mitteilungen" beim Fehlerliste kann man immer ignorieren?
> Manchmal habe ich hunderten davon gesehen aber das Programm funktionierte in Ordnung...
> Wann könnten sie wichtig sein?
> 
> Danke im Voraus,
> Andrés

Es gibt wie du bestimmt schon gesehen hast 3 Stufen: Fehler, Warnung und Mitteilung. 
-  Bei `Fehler` wird das Projekt nicht erstellt und du musst aktiv werden. 
-  Bei `Warnung` sagt dir der Compiler das etwas nicht in Ordnung ist, aber zwingt dich nicht aktiv zu werden. Trotzdem ist es sinnvoll alle `Warnungen` zu beheben, weil sie zu Problemen zur Laufzeit führen können.
- Bei `Mitteilungen` geht es darum, dass Visual Studio dir Vorschläge macht wie du deinen Quellcode verbessern kannst. Dies kann das Fehlerrisiko senken (z.B. schlägt Visual Studio häufig vor, dass ein Attribut auf `readonly` gesetzt werden kann), die Performance verbessern, die Kompatibilität deines Quellcode erhöhen, ...

Wie du vielleicht schon gesehen hast, können sowohl `Warnung` wie auch `Mitteilung` sehr schnell, sehr viel werden. Daher ist es natürlich verlockend sie einfach zu ignorieren. Aus eigener Erfahrung kann ich dir allerdings nur davon abraten viele Mitteilungen und Warnungen mit dir rum zu schleppen. Alles was dort angeboten wird hilft deinen Quellcode besser zu machen. Bist du der Ansicht, dass ein Hinweis der dir häufiger angezeigt wird für dich nicht relevant ist, dann kannst du ihn explizit für ein Projekt oder für eine Codestelle ausschalten. Damit sehen andere Entwickler, dass du dich mit dem Thema beschäftigt hast und einen Grund hast, warum du der Meinung bist gegen Visual Studios Empfehlung zu handeln.

**Comment by AndresRedondo87** [comment]
Vielen Dank für die schnelle Antworten :)
