### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by zondarg** [LMStudent/hallo-github#167]
Hallo und danke für den Kurs!
#153 hat es ja schon zusammengefasst. :+1: 
Und *Markdown* funktioniert auch.

**Comment by zondarg** [comment]
Und geschlossen.

**Comment by suchja** [comment]
@zondarg Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Wie du schon festgestellt hast, kannst du dieses Issue auch wieder schließen. Neben dir kann das nur der Projektinhaber (also in diesem Fall ich). Du kannst allerdings auch an geschlossenen Issues kommentieren (so wie ich das gerade mache). Das macht manchmal Sinn, wenn du noch weitere Informationen zum Thema hast oder wünschst, dass ein geschlossenes Issue wieder geöffnet wird.

Wenn du das Issue selber geschrieben hast, dann kannst du es auch wieder öffnen. Wenn du magst, kannst du das ja noch ausprobieren (und dann auch bitte gleich wieder schließen, dann habe ich weniger Arbeit 😉).

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
