### ISSUE TITLE
Test Issue für Udemy Kurs

### ISSUE THREAD

**Issue by st-klockow** [LMStudent/hallo-github#172]
Hallo @suchja (Jan), ich mache gerade die Aufgabe: "erstelle ein Issue". Dein Kurs auf Udemy ist echt super. Es bringt mich weiter und dafür bin ich sehr dankbar. 

Ich wünsche dir eine schöne Woche. 

Gruß Steve

**Comment by st-klockow** [comment]
das war nur ein Test Issue

**Comment by suchja** [comment]
Hallo Steve,

ich finde super, dass du auch die Übungen machst. Momentan bin ich gerade sehr beschäftigt daher bin ich mit der persönlichen Antwort ziemlich hinterher. Hoffe es hat dir trotzdem was gebracht. Hast du den PullRequest auch gemacht? Ich werde es gleich sehen ;-).

Viele Grüße aus Bielefeld
Jan von LernMoment.de

**Comment by st-klockow** [comment]
Hallo Jan,

ist ja klasse, dass du mir wirklich antwortest. Danke für diesen Service,
das ist echt nett.

Ich weiß ehrlich gesagt nicht mehr ob ich den Pull Request auch gemacht
habe, aber bestimmt. Dein Kurs hat mir sehr geholfen.

Ich wünsche dir ein schönes Wochenende und sende dir verregnete Grüße aus
dem eigentlich schönen Berlin.

Am Sa., 26. Sept. 2020 um 17:18 Uhr schrieb Jan Suchotzki <
notifications@github.com>:
