### ISSUE TITLE
ZWEITES ISSUE

### ISSUE THREAD

**Issue by Joachim27** [LMStudent/hallo-github#216]
@suchja 
Ich bin Joachim und bin über UDEMY auf Deinen super gut gemachten Kurs gestoßen. LEider habe ich mein erstes Issue auf der falschen Seite bzw. Bereich eingegeben. Daher die Überschrift 'ZWEITES ISSUE'. Ich finde es sehr schön, dass sich jemand soviel Mühe macht, einen solchen Kurs auf die Beine zu stellen. Wir werden uns sicher noch bei anderen Gelegenheiten über den Weg laufen.

**Comment by Joachim27** [comment]
@suchja 
Habe wunschgemäß das Problem geschlossen, werde Deinem Udemy-Kurs I weiter folgen. Vielen Dank für die Unterstützung und noch eine schöne Zeit!

**Comment by suchja** [comment]
@Joachim27 SUPER! Weiter so ;-)!
