### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by karimabd84** [LMStudent/hallo-github#23]
@suchja  Thank you very much for the free tutorials in Udemy...

**Comment by suchja** [comment]
@karimabd84 You are more then welcome! Did you try to use some of the markdown syntax to format the text here in the issue? I do explain some more details [in this video](https://www.youtube.com/watch?v=TzyHMDYhQL8).

As author of this issue you can also close it. Give it a try! Once you get the hang of *issues*, you can also practice *pull requests* here in this repositories. Looking forward to help you!

**Comment by karimabd84** [comment]
Super!
