### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by fwesselmann** [LMStudent/hallo-github#232]
Hallo,
danke für den Kurs! 

Gruß

**Comment by fwesselmann** [comment]
Hallo Lernbot,
dann schließe ich mal das Issue.
Grüße

**Comment by suchja** [comment]
Auch von mir ein persönliches Hallo! Schön das du so aktiv bist. Weiterhin viel Spaß auf GitHub und melde dich, wenn du fragen hast. 

Viele Grüße 
Jan von LernMoment.de
