### ISSUE TITLE
Mein erstes Issue als Udemy Student

### ISSUE THREAD

**Issue by martinho22** [LMStudent/hallo-github#24]
Hi @suchja,
dann leg ich doch auch mal ein Issue an...

Grüße
Martin

**Comment by martinho22** [comment]
...und um's nich zu anstrengend zu manchen schließe ich's auch wieder

**Comment by suchja** [comment]
@martinho22 das ist ja alles perfekt hier bei dir. Da brauchst du wohl keine Unterstützung 😉 

Wenn du lernen möchtest wie du mit Markdown den Text in einem Issue formatierst, dann kannst du dir [dieses Video](https://www.youtube.com/watch?v=TzyHMDYhQL8) anschauen. Darin erkläre ich noch einiges. Du kannst natürlich auch die Formatierungselemente hier beim Issue-Editor verwenden, aber wenn du die Markdown-Syntax kennst, bist du schneller und hast auch mehr Möglichkeiten.

Dir viel Spaß und ich hoffe du machst auch einen PullRequest.
