### ISSUE TITLE
Mein erstes Issue

### ISSUE THREAD

**Issue by Sukramg** [LMStudent/hallo-github#252]
Hallo Jan, 
vielen Dank für deinen kostenlosen Kurs. Habe woanders gelesen, dass du noch einen 2. Kurs anbietest.
Grüße
ML

**Comment by Sukramg** [comment]
Alles klar!

**Comment by suchja** [comment]
@Sukramg Hallo Markus,

freut mich, dass dir mein Kurs gefällt. Alle Kurse von mir findest du auf [LernMoment](https://www.lernmoment.de/kurse/).

Wie du siehst, ist es auch möglich an einem Issue zu kommentieren, wenn es bereits geschlossen ist. Bei Bedarf könnte einer von uns beiden das Issue auch wieder öffnen über den *Reopen* Button.

Ich wünsche dir noch ein schönes Rest-Wochenende.

Mit sonnigen Grüßen aus Bielefeld
Jan von LernMoment.de
