### ISSUE TITLE
Uebung_01

### ISSUE THREAD

**Issue by Tachiguro** [LMStudent/hallo-github#31]
Bin gerade beim GitHub entdecken.
Die Idee zur Challenge finde ich sehr geil. Weil meistens fällt einen nix ein. (ich bin mir bewusst das es nicht her gehört).

MfG 
Tachi ò_ó

**Comment by suchja** [comment]
SEHR gut! 👏 

Am besten du schließt dieses Issue selber mal. Ein kleiner Klick für dich, ein großer Schritt für ... ;-)

**Comment by suchja** [comment]
Übrigens, wenn du jemanden per Mentions (z.B. @Tachiguro ) direkt "ansprichst", dann bekommt derjenige eine eMail geschickt.
