### ISSUE TITLE
Übung-Issue

### ISSUE THREAD

**Issue by nionita** [LMStudent/hallo-github#34]
@suchja Das ist eine Übung! Danke für den Udemy Kurs :-)

**Comment by suchja** [comment]
Sehr gerne, freut mich, wenn es dir hilft und gefällt!

**Comment by suchja** [comment]
Als Autor kannst du übrigens ein Issue schließen. Probier es doch gleich mal aus!

**Comment by nionita** [comment]
Issue kann geschlossen werden.
