### ISSUE TITLE
Danke für den Kurs!

### ISSUE THREAD

**Issue by nils-v** [LMStudent/hallo-github#36]
@suchja Danke für den Crash-Kurs zu github!

**Comment by suchja** [comment]
Sehr gerne! Freut mich, dass du selber aktiv wirst unsachlich die Übungen machst. Weiterhin viel Spaß und Erfolg 

Jan von LernMoment.de

PS: Du also Autor des Issues kannst es auch wieder schließen. Probier es doch gleich mal aus.

**Comment by nils-v** [comment]
Mach ich!

**Comment by suchja** [comment]
SUPER!

Wie du siehst können noch weitere Kommentare dem Issue hinzugefügt werden, auch wenn es geschlossen ist. Der Workflow erlaubt es auch, dass ein geschlossenes Issue nochmals wieder geöffnet wird.
