### ISSUE TITLE
Ein Test-Issue

### ISSUE THREAD

**Issue by farahzeb** [LMStudent/hallo-github#37]
Hi @suchja 
Das ist nur ein Test-Issue für das Github Tutorial! Danke für das tolle Tutorial, so far :)

- [ ] Delete this new issue.

**Comment by suchja** [comment]
@farahzeb Sehr gerne :smile: !!!

Als Author dieses Issues kannst du es übrigens auch wieder schließen. Probier es doch gleich mal aus.

**Comment by suchja** [comment]
@farahzeb PERFEKT! Super Start auf GitHub 🚀
