### ISSUE TITLE
Erstes, eigenes Test-Issue

### ISSUE THREAD

**Issue by klochden** [LMStudent/hallo-github#49]
@suchja 
Nur zum testen :-)
**ÜBUNG:** Erstelle ein Issue
_Abschnitt 2, Lektion 6_

**Comment by suchja** [comment]
@klochden SUPER! Erfolgreich absolviert!

Wir beide, du als Autor und ich als Projektinhaber, haben das Recht dieses Issue wieder zu schliessen. Magst du es mal ausprobieren?

Viele Grüße
Jan von LernMoment.de

------------------------
🚀 NEU von LernMoment: Übe mit mir professionelle Softwareentwicklung in C# - [Starte jetzt zum Einführungspreis](https://www.udemy.com/csharp-uebungskurs-einfach-verschluesselt/?couponCode=GH-FOOTER-UROT-10)
