### ISSUE TITLE
Kurs Issue Aufgabe

### ISSUE THREAD

**Issue by appOdrome** [LMStudent/hallo-github#5]
@LMStudent 

das ist die gewünschte Issue-Meldung aus dem Online-Kurs: Einstieg in GitHub: Entwickle Software wie die Profis.

Frage: Wer schließt die Issues? können das alle Teammitglieder? Kann man einmal geschloßene Issues auch wieder öffnen?

Da ich in Android-Studio arbeite kann ich mir die Visual Studio c# Codes leider nicht anschauen.

**Comment by suchja** [comment]
@appOdrome 

Super, dass du die Aufgabe gemacht hast. Die Anwendung ausführen ist natürlich kein muss. Werde mal die aktuelle Version als Release einstellen, dann kannst du die Anwendung als "Exe" unter Windows direkt ausführen auch ohne Visual Studio.

Bezüglich deiner Fragen:

> Wer schließt die Issues? können das alle Teammitglieder?

JA, es können alle Teammitglieder und in diesem Fall auch du als derjenige, der das Issue erstellt hat. -> Probiere es doch gleich mal aus!

> Kann man einmal geschlossene Issues auch wieder öffnen?

JA, auf jeden Fall kann es das Team. Wenn ich mich richtig erinnere sollte es auch der "Autor" (also in diesem Fall wieder du) können. -> Auch das kannst du dann ja mal ausprobieren.

**Comment by suchja** [comment]
Ich denke du weist mittlerweile wie ein Issue geschlossen wird ;-)
