### ISSUE TITLE
Rechtschreibung im README

### ISSUE THREAD

**Issue by rocketboy376** [LMStudent/hallo-github#65]
Bin gerade bei der Udemy-Übung "Erstelle ein Issue" und hab im Readme-File gleich mal nach ein paar Fehlern gesucht (und auch gefunden ;-). Die Kommafehler lass ich jetzt mal alle außen vor, aber was vielleicht korrigiert werden müsste ist die Abkürzung für "American Standard Code for Information Interchange" --> ASCII. Das muss mE immer groß geschrieben werden, da es eben eine Abkürzung ist.

**Comment by suchja** [comment]
@rocketboy376 Vielen Dank für den Hinweis!

Wie du sehen kannst habe ich dieses Issue direkt aus einem Commit geschlossen.

**Comment by rocketboy376** [comment]
@suchja Super, danke dir!
