### ISSUE TITLE
Toller Kurs bisher

### ISSUE THREAD

**Issue by aueb** [LMStudent/hallo-github#68]
wüsste jetzt nicht was ich bemängeln sollte :-)

**Comment by suchja** [comment]
@aueb Vielen Dank 👍

Wenn du magst, dann kannst du als Autor dieses Issue auch wieder schließen. Außer dir kann das nur der Projektinhaber (in diesem Fall also ich ;).

Weiterhin viel Spaß mit dem Kurs und ich hoffe du kannst GitHub zu deinem Vorteil nutzen.

Viele Grüße
Jan

**Comment by suchja** [comment]
@aueb DANKE!

Wie du siehst, kann auch nachdem ein Issue geschlossen wurde noch daran kommentiert werden. Je nach Bedarf kann das Issue auch wieder geöffnet werden.
