### ISSUE TITLE
github-Kurs

### ISSUE THREAD

**Issue by celalbyk** [LMStudent/hallo-github#72]
#Gruß aus Köln, toller Kurs.

**Comment by suchja** [comment]
@celalbyk Hallo und herzlich willkommen! Freut mich sehr, dass der Kurs dir gefällt. Hoffe du machst die weiteren Übungen auch noch. Vielen lieben Dank für deine tolle Bewertung auf [Udemy](https://www.udemy.com/github-tutorial-deutsch/)!

Dir ganz viel Spaß und Erfolg mit GitHub
Jan von LernMoment.de
