### ISSUE TITLE
Lob für den udemy-Kurs

### ISSUE THREAD

**Issue by KuehnleB** [LMStudent/hallo-github#74]
@suchja Ausgesprochen gut gelungen der Einstieg in die Git/Github-Thematik. Macht auch Spaß, Dir zuzuhören, denn eine gute Sprache ist Voraussetzung, dass man als Lernender dran bleiben kann und nicht von holprigem Sprech genervt wird. 

Danke und weiter so!
KuehnleB

**Comment by suchja** [comment]
@KuehnleB **VIELEN LIEBEN DANK!!!** 👍

Freut mich sehr, dass du mit dem Kurs zurecht kommst und das er dir hilft! Außerdem ist es sehr gut, dass du aktiv wirst und auch was auf GitHub umsetzt. Schließlich geht es auch darum Erfahrung zu sammeln.

Du, als Author dieses Issues, kannst es übrigens, genau wie ich als Projektinhaber, wieder schließen. Probier es doch gleich mal aus!

Viele Grüße
Jan von [LernMoment.de](https://www.lernmoment.de)

**Comment by KuehnleB** [comment]
Danke für die schnelle Rückmeldung und Tschüss!
