### ISSUE TITLE
Optionales Komma

### ISSUE THREAD

**Issue by ulffischer** [LMStudent/hallo-github#78]
Hallo @suchja 
in [README.md](https://github.com/LMStudent/hallo-github/blob/master/README.md) könntest du im vorletzten Absatz noch ein Komma einsetzen. Ich glaube, das ist nach den aktuellen Regeln optional, aber es könnte die Lesbarkeit steigern.

Der Satz würde dann so aussehen:

Darüberhinaus lernst du im Kurs alles was du benötigst**,** um an Open-Source-Projekten zu arbeiten oder dir selber Hilfe aus der Community zu holen.

**Comment by ulffischer** [comment]
Ok :-) mache ich

**Comment by suchja** [comment]
DANKE!
