### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by s7git** [LMStudent/hallo-github#8]
nur ein Test lt. Aufgabe aus dem Udemy Kurs so wie hier #5

**Comment by suchja** [comment]
@s7git HERZLICHEN GLÜCKWUNSCH!

Nicht nur ein Issue erstellt sondern auch gleich mit einem bestehenden verlinkt. Ich habe es erst jetzt gesehen, weil du mich nicht direkt referenziert (mention über das @) hast. Ansonsten hätte ich direkt eine Mail bekommen.

**Comment by suchja** [comment]
Wenn du magst, dann kannst du dieses Issue auch wieder schließen.

**Comment by s7git** [comment]
@suchja - ok ich beende ... Danke für die Hilfe

**Comment by suchja** [comment]
@s7git Super! Übrigens kannst du auch Kommentare an einem bereits geschlossenen Issue hinterlassen.
