### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by denschiro** [LMStudent/hallo-github#86]
@suchja Dies ist ein Test , danke für den Udemy Kurs

**Comment by suchja** [comment]
@denschiro SEHR gerne! Freut mich, dass er dir geholfen hat.

Übrigens du als Autor dieses Issues kannst es auch wieder schließen. Ausser dem Autor kann das nur der Projektinhaber. Probier du es doch gleich mal aus.

PS: Natürlich freue ich mich über eine Bewertung meines Kurses bei Udemy 😉!

**Comment by denschiro** [comment]
Close
