### ISSUE TITLE
Lob für den tollen Kurs

### ISSUE THREAD

**Issue by SirHenry34** [LMStudent/hallo-github#89]
@suchja Ich kann mich dem Lob von #74 nur anschließen. Mach weiter so.

**Comment by suchja** [comment]
@SirHenry34 Vielen Dank! Freut mich sehr das du dabei bist und Glückwunsch zum ersten Issue!
Magst du es gleich wieder schließen und dann mit einem PullRequest voran schreiten? 😉

**Comment by SirHenry34** [comment]
Danke für den Kurs
