### ISSUE TITLE
issue template missing

### ISSUE THREAD

**Issue by diemau** [LMStudent/hallo-github#99]
@suchja ich finde kein Template zum Erstellen von issues. 
PS: komme von udemy ;)

**Comment by suchja** [comment]
@diemau Willkommen auf GitHub! Freut mich sehr, dass du mit meinem Udemy-Kurs dich in GitHub einarbeitest.

Die Templates musst du selber für ein Repository erstellen. Dafür kannst du entweder den Template-Builder benutzen (den du in den Einstellungen für das Repository findest) oder du kannst ein Template auch manuell anlegen. Weitere Informationen findest du in [dieser Beschreibung](https://help.github.com/en/articles/about-issue-and-pull-request-templates).

Solltest du damit irgendwie Probleme haben, dann sag bitte einfach nochmals Bescheid.

**Comment by suchja** [comment]
Ich hoffe ich konnte deine Frage lösen.
